### ISSUE TITLE
live chat breaks in production but not locally

### ISSUE THREAD

**Issue by hamdaankhalid** [hamdaankhalid/LiveStreaming-And-Chat#6]
issue seems to be when we. emit an object it sends only a string to new-message

**Comment by deriegle** [comment]
I think we may need to JSON.parse the data payload inside the client index.js.

Sorry about that!

**Comment by hamdaankhalid** [comment]
aww devin no worries, just some deployment related environment  issue, I fixed 👍🏽 this now all good
